---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "balance-transfer"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "Balance Transfer Network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see org1.yaml and org2.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  mychannel:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("org1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer0.ordererorg1
      - orderer1.ordererorg1
      - orderer2.ordererorg1

    # Required. list of peers from participating orgs
    peers:
      peer0.org-mtbc:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer1.org-mtbc:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

      peer0.org-uni:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer1.org-uni:
        endorsingPeer: false
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: false

    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - mycc:v0

#
# list of participating organizations in this network
#
organizations:
  org-mtbc:
    mspid: org-mtbcMSP

    peers:
      - peer0.org-mtbc
      - peer1.org-mtbc

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca.org-mtbc

    # [Optional]. If the application is going to make requests that are reserved to organization
    # administrators, including creating/updating channels, installing/instantiating chaincodes, it
    # must have access to the admin identity represented by the private key and signing certificate.
    # Both properties can be the PEM string or local path to the PEM file. Note that this is mainly for
    # convenience in development mode, production systems should not expose sensitive information
    # this way. The SDK should allow applications to set the org admin identity via APIs, and only use
    # this route as an alternative when it exists.
    adminPrivateKey:
      path:  /tmp/fabric/crypto-config/peerOrganizations/org-mtbc/users/Admin@org-mtbc/msp/keystore/d2be603b60332816964d46780bc40e0489b39762132c138264412508407fd2db_sk
    signedCert:
      path: /tmp/fabric/crypto-config/peerOrganizations/org-mtbc/users/Admin@org-mtbc/msp/signcerts/Admin@org-mtbc-cert.pem

  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  org-uni:
    mspid: org-uniMSP
    peers:
      - peer0.org-uni
      - peer1.org-uni
    certificateAuthorities:
      - ca.org-uni
    adminPrivateKey:
      path: /tmp/fabric/crypto-config/peerOrganizations/org-uni/users/Admin@org-uni/msp/keystore/e9678fcc158cbab6c4c1efb796d829dccd528ae74e69b545bc3b83b0a412ac23_sk
    signedCert:
      path: /tmp/fabric/crypto-config/peerOrganizations/org-uni/users/Admin@org-uni/msp/signcerts/Admin@org-uni-cert.pem

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer0.ordererorg1:
    url: grpcs://10.20.35.21:32000

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer0.ordererorg1

    tlsCACerts:
      path: /tmp/fabric/crypto-config/ordererOrganizations/ordererorg1/orderers/orderer0.ordererorg1/tls/ca.crt
  orderer1.ordererorg1:
    url: grpcs://10.20.35.21:32001

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer1.ordererorg1

    tlsCACerts:
      path: /tmp/fabric/crypto-config/ordererOrganizations/ordererorg1/orderers/orderer1.ordererorg1/tls/ca.crt

  orderer2.ordererorg1:
    url: grpcs://10.20.35.21:32002

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer2.ordererorg1

    tlsCACerts:
      path: /tmp/fabric/crypto-config/ordererOrganizations/ordererorg1/orderers/orderer2.ordererorg1/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.org-mtbc:
    # this URL is used to send endorsement and query requests
    url: grpcs://10.20.35.21:30001

    grpcOptions:
      ssl-target-name-override: peer0.org-mtbc
    tlsCACerts:
      path: /tmp/fabric/crypto-config/peerOrganizations/org-mtbc/peers/peer0.org-mtbc/tls/ca.crt

  peer1.org-mtbc:
    url: grpcs://10.20.35.21:30004
    grpcOptions:
      ssl-target-name-override: peer1.org-mtbc
    tlsCACerts:
      path: /tmp/fabric/crypto-config/peerOrganizations/org-mtbc/peers/peer1.org-mtbc/tls/ca.crt

  peer0.org-uni:
    url: grpcs://10.20.35.21:30101
    grpcOptions:
      ssl-target-name-override: peer0.org-uni
    tlsCACerts:
      path: /tmp/fabric/crypto-config/peerOrganizations/org-uni/peers/peer0.org-uni/tls/ca.crt

  peer1.org-uni:
    url: grpcs://10.20.35.21:30104
    eventUrl: grpcs://10.34.0.8:7053
    grpcOptions:
      ssl-target-name-override: peer1.org-uni
    tlsCACerts:
      path: /tmp/fabric/crypto-config/peerOrganizations/org-uni/peers/peer1.org-uni/tls/ca.crt

#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca.org-mtbc:
    url: https://10.20.35.21:30054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: /tmp/fabric/crypto-config/peerOrganizations/org-mtbc/ca/ca.org-mtbc-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca

  ca.org-uni:
    url: https://10.20.35.21:30154
    httpOptions:
      verify: false
    tlsCACerts:
      path: /tmp/fabric/crypto-config/peerOrganizations/org-uni/ca/ca.org-uni-cert.pem
    registrar:
      - enrollId: admin
        enrollSecret: adminpw
    # [Optional] The optional name of the CA.
    caName: ca
